# Generated by Django 5.0.3 on 2024-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college',
            new_name='college_name',
        ),
    ]
